// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBoaeE9YUqVyKjqLqafo5od0L15boue84s',
    appId: '1:291518603261:web:33d977b8caf83223790394',
    messagingSenderId: '291518603261',
    projectId: 'gojob-73262',
    authDomain: 'gojob-73262.firebaseapp.com',
    storageBucket: 'gojob-73262.appspot.com',
    measurementId: 'G-PQK8ZHCKK9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBjvaa97tePrbVztcfOW9pX1SYlZx-tmAg',
    appId: '1:291518603261:android:40d0bf6698c65926790394',
    messagingSenderId: '291518603261',
    projectId: 'gojob-73262',
    storageBucket: 'gojob-73262.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC1k6S9Qkeiy5khU6kJoCWakWpBixH6kUw',
    appId: '1:291518603261:ios:8a62ceda277f2aed790394',
    messagingSenderId: '291518603261',
    projectId: 'gojob-73262',
    storageBucket: 'gojob-73262.appspot.com',
    iosBundleId: 'com.example.goJob',
  );
}
